name: cs
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - numba
  - networkx
  - jupyter
  - autograd
  - pylops
  - pyproximal
  - scikit-learn
  - pyarrow
  - scip
  - cvxpy
  - cvxopt
  - tqdm
  - wandb
  - hydra
  - pip:
    - picos
    - pymanopt
    - gstools
    - PyWavelets